language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

sudo: false

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer install

script: ./vendor/bin/phpunit -c phpunit.xml.dist
